CREATE DATABSE clickerDB DEFAULT CHARACTER SET utf8;

USE clickerDB;

CREATE TABLE high_score (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  score INT NOT NULL,
  PRIMARY KEY (id));